### ISSUE TITLE
[Request] Make findByIndex return Iterable<DataRow>

### ISSUE THREAD

**Issue by dirmeier** [nRo/DataFrame#1]
Hey Alex,

if I am putting an index on my DataFrame I can search for a row like this:
```java
dataFrame.addIndex("idx", "barcode")
DataRow row = dataFrame.findByIndex("idx", "barcode1");
```
However, in some cases multiple rows are returned. So ideally it could return sth like:
```java
Iterable<DataRow> row = dataFrame.findByIndex("idx", "barcode1");
```
Could you maybe add this.

Best, Simon

**Comment by nRo** [comment]
Hi Simon,

thanks for your suggestion. 
Multi-row indices are added in the current version (0.6): e65b802cbf1e99876e6d7a46cd1b3badc6305d94

Example
```java
List<DataRow> row = dataFrame.findByIndex("idx", "barcode1");
```

**Comment by dirmeier** [comment]
Sweet!
