### ISSUE TITLE
Initialization of the parser map is not thread-safe

### ISSUE THREAD

**Issue by ProjectMoon** [nRo/DataFrame#4]
Discovered this while adding columns to data frames in a multi threaded environment. Each thread has its own frame, so concurrency should not be an issue. However, `ParserUtil#getParserMap()` and `ParserUtil#init()` are not thread-safe. The lazy initialization of parserMap can lead to unexpected "Parser not found" errors when adding columns to multiple frames in multiple threads. This occurs because the `if (parserMap == null)` check no longer triggers (since the map has been created by `init()`), but the map is not done initializing.

From just looking at ParserUtil.java, it doesn't seem like there is a reason to lazily initialize this. Making the parser map `static final` and initializing it in a `static` block seems like a good solution that avoids multi-threading issues.

**Comment by nRo** [comment]
Thanks for reporting,
should be fixed in 7a355d84d2b73b5c5f99984e0afcbb850859494e
The parserMap is static final and initialized in a static block.

**Comment by ProjectMoon** [comment]
Cool. Do you plan on making a new release to Maven Central?

**Comment by nRo** [comment]
there will be a new release in the near future.

**Comment by nRo** [comment]
I just submitted a new release (0.7.1) to maven central.
